{% set name = "fps-akernel-task" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_akernel_task-{{ version }}.tar.gz
  sha256: bb5080dbf918644f2fcde6a0fdbf6f03f238985b2971e49587df34ee6c5df269

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.15.0,<0.16.0
    - anyio
    - akernel >=0.4.0

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - fps_akernel_task

about:
  home: https://github.com/davidbrochart/akernel/tree/main/plugins/akernel_task
  summary: An FPS plugin for the kernel task API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/davidbrochart/akernel/tree/main/plugins/akernel_task
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
