schema_version: 1

context:
  name: fps-akernel-task
  version: "0.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fps_akernel_task-${{ version }}.tar.gz
  sha256: 98ef9ec89f1227d09b0469f3c9adeb01e1f1fa6f30ccb6add9dcbeed8891d7ed

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - jupyverse-api >=0.15.0,<0.16.0
    - anyio
    - akernel >=0.4.1

tests:
  - python:
      imports:
        - fps_akernel_task
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: An FPS plugin for the kernel task API
  license_file: LICENSE
  license: MIT
  homepage: https://github.com/davidbrochart/akernel/tree/main/plugins/akernel_task
  repository: https://github.com/davidbrochart/akernel/tree/main/plugins/akernel_task

extra:
  recipe-maintainers:
    - davidbrochart
